name: Build and Publish to PyPI

on:
  push:
    branches: [main]
    paths:
      - "src/coastalbook/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/envs/311-package.yaml

      - name: Build package
        run: |
          poetry install
          poetry build

      # Publish to TestPyPI first
      - name: Publish to TestPyPI
        run: |
          poetry publish --repository testpypi -u __token__ -p ${{ secrets.TEST_PYPI_API_TOKEN }}

      # Test install from TestPyPI
      - name: Test install from TestPyPI
        run: |
          pip install \
          --index-url https://test.pypi.org/simple/ \
          --extra-index-url https://pypi.org/simple \
          coastalbook

      # Publish to PyPI
      - name: Publish to PyPI
        run: |
          poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
